services:
  - type: web
    name: fatigue-detection
    runtime: python
    buildCommand: pip install -r server/requirements.txt
    startCommand: cd server && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0